name: Publish to NuGet

on:
  release:
    branches: [ main ]
    types: [ published ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master
    
    - name: Setup dotnet tooling
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: '6.0.x'
    
    - name: Restore dependencies
      run:           
          dotnet restore

    - name: Compile
      run: dotnet build NVerilogParser\NVerilogParser.csproj --configuration Release --no-restore

    - name: Publish to NuGet
      env:
        APIKEY: ${{ secrets.NUGET_APIKEY }}
      run: dotnet nuget push NVerilogParser\bin\Release\NVerilogParser.*.nupkg -k $env:APIKEY -s "https://api.nuget.org/v3/index.json"
